quarkus.http.port=8082

# Conexão com FIPE
quarkus.rest-client.fipe-api.url=https://parallelum.com.br/fipe/api/v1

# Conexão RabbitMQ (Entrada)
mp.messaging.incoming.marcas-in.connector=smallrye-rabbitmq
mp.messaging.incoming.marcas-in.queue.name=fipe-queue
mp.messaging.incoming.marcas-in.exchange.name=fipe-exchange
mp.messaging.incoming.marcas-in.routing-key=marca-key

# Conexão Banco de Dados
quarkus.datasource.db-kind=postgresql
# Em Dev, usa localhost. No Docker, o environment variable sobrescreve isso.
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fipe_db
quarkus.datasource.username=usrdb
quarkus.datasource.password=pwd123
# Cria as tabelas automaticamente
quarkus.hibernate-orm.database.generation=update