quarkus.http.port=8082
quarkus.rest-client.fipe-api.url=https://parallelum.com.br/fipe/api/v1

mp.messaging.connector.smallrye-rabbitmq.host=${RABBITMQ_HOST:localhost}
mp.messaging.connector.smallrye-rabbitmq.port=5672
mp.messaging.connector.smallrye-rabbitmq.username=${RABBITMQ_USER:guest}
mp.messaging.connector.smallrye-rabbitmq.password=${RABBITMQ_PASSWORD:guest}

mp.messaging.incoming.marcas-in.connector=smallrye-rabbitmq
mp.messaging.incoming.marcas-in.queue.name=fipe-queue
mp.messaging.incoming.marcas-in.exchange.name=fipe-exchange
mp.messaging.incoming.marcas-in.routing-key=marca-key

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:5432/fipe_db
quarkus.datasource.username=${DB_USER:usrdb}
quarkus.datasource.password=${DB_PASS:pwd123}
quarkus.hibernate-orm.database.generation=update

quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true