quarkus.http.port=8081

# Configuração RabbitMQ (Envio)
mp.messaging.outgoing.marcas-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.marcas-out.exchange.name=fipe-exchange
mp.messaging.outgoing.marcas-out.routing-key=marca-key

# Banco de dados (Leitura)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fipe_db

# API FIPE Externa [cite: 8]
quarkus.rest-client.fipe-api.url=https://parallelum.com.br/fipe/api/v1