quarkus.http.port=8081
quarkus.rest-client.fipe-api.url=https://parallelum.com.br/fipe/api/v1
mp.messaging.outgoing.marcas-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.marcas-out.exchange.name=fipe-exchange
mp.messaging.outgoing.marcas-out.routing-key=marca-key
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=usrdb
quarkus.datasource.password=pwd123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fipe_db
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
