CREATE TABLE IF NOT EXISTS VeiculoEntity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigoMarca VARCHAR(255),
    nomeMarca VARCHAR(255),
    codigoModelo VARCHAR(255),
    nomeModelo VARCHAR(255),
    observacoes TEXT
);

INSERT INTO VeiculoEntity (codigoMarca, nomeMarca, codigoModelo, nomeModelo, observacoes) VALUES 
('21', 'Fiat', '456', 'Palio Fire 1.0', 'Carro de entrada, manutenção barata'),
('21', 'Fiat', '888', 'Toro Volcano Diesel', 'Pickup robusta, boa para carga'),
('21', 'Fiat', '999', 'Uno Mille Way', 'Econômico e aguenta estrada de terra'),
('23', 'GM - Chevrolet', '789', 'Onix Turbo Premier', 'Líder de vendas, wi-fi a bordo'),
('23', 'GM - Chevrolet', '111', 'Tracker LTZ', 'SUV compacto urbano'),
('23', 'GM - Chevrolet', '222', 'S10 High Country', 'Pickup grande, consumo alto'),
('59', 'VW - Volkswagen', '333', 'Gol 1.6 MSI', 'Clássico do mercado brasileiro'),
('59', 'VW - Volkswagen', '444', 'Nivus Highline', 'Design coupé moderno'),
('59', 'VW - Volkswagen', '555', 'Jetta GLI', 'Sedan esportivo de alta performance'),
('59', 'VW - Volkswagen', '666', 'T-Cross Sense', 'Versão PCD popular'),
('25', 'Honda', '123', 'Civic Touring', 'Sedan médio confiável'),
('25', 'Honda', '124', 'HR-V EXL', 'SUV com bom valor de revenda'),
('25', 'Honda', '125', 'City Hatchback', 'Espaço interno modular'),
('56', 'Toyota', '777', 'Corolla Altis Hybrid', 'Muito econômico na cidade'),
('56', 'Toyota', '778', 'Hilux SRX', 'Indestrutível, muito valorizada'),
('56', 'Toyota', '779', 'Yaris XLS', 'Compacto premium'),
('6', 'Audi', '001', 'A3 Sedan S-Line', 'Luxo de entrada'),
('6', 'Audi', '002', 'Q5 Sportback', 'SUV de luxo esportivo'),
('7', 'BMW', '003', '320i M Sport', 'Tração traseira, dirigibilidade'),
('26', 'Hyundai', '901', 'HB20 Platinum', 'Design polêmico mas bem equipado'),
('26', 'Hyundai', '902', 'Creta Ultimate', 'Tecnologia de ponta no segmento');